/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import '@stencil/core';




export namespace Components {

  interface StencilVenn {
    'intersection_value': string;
    'left': string;
    'left_value': string;
    'right': string;
    'right_value': string;
    'scale': number;
  }
  interface StencilVennAttributes extends StencilHTMLAttributes {
    'intersection_value'?: string;
    'left'?: string;
    'left_value'?: string;
    'right'?: string;
    'right_value'?: string;
    'scale'?: number;
  }
}

declare global {
  interface StencilElementInterfaces {
    'StencilVenn': Components.StencilVenn;
  }

  interface StencilIntrinsicElements {
    'stencil-venn': Components.StencilVennAttributes;
  }


  interface HTMLStencilVennElement extends Components.StencilVenn, HTMLStencilElement {}
  var HTMLStencilVennElement: {
    prototype: HTMLStencilVennElement;
    new (): HTMLStencilVennElement;
  };

  interface HTMLElementTagNameMap {
    'stencil-venn': HTMLStencilVennElement
  }

  interface ElementTagNameMap {
    'stencil-venn': HTMLStencilVennElement;
  }


  export namespace JSX {
    export interface Element {}
    export interface IntrinsicElements extends StencilIntrinsicElements {
      [tagName: string]: any;
    }
  }
  export interface HTMLAttributes extends StencilHTMLAttributes {}

}
