/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import '@stencil/core';




export namespace Components {

  interface StencilVenn2 {
    'labels': string;
    'scale': number;
    'values': string;
  }
  interface StencilVenn2Attributes extends StencilHTMLAttributes {
    'labels'?: string;
    'scale'?: number;
    'values'?: string;
  }

  interface StencilVenn3 {
    'labels': string;
    'scale': number;
    'values': string;
  }
  interface StencilVenn3Attributes extends StencilHTMLAttributes {
    'labels'?: string;
    'scale'?: number;
    'values'?: string;
  }

  interface StencilVenn {
    'labels': string;
    'scale': number;
    'values': string;
  }
  interface StencilVennAttributes extends StencilHTMLAttributes {
    'labels'?: string;
    'scale'?: number;
    'values'?: string;
  }
}

declare global {
  interface StencilElementInterfaces {
    'StencilVenn2': Components.StencilVenn2;
    'StencilVenn3': Components.StencilVenn3;
    'StencilVenn': Components.StencilVenn;
  }

  interface StencilIntrinsicElements {
    'stencil-venn-2': Components.StencilVenn2Attributes;
    'stencil-venn-3': Components.StencilVenn3Attributes;
    'stencil-venn': Components.StencilVennAttributes;
  }


  interface HTMLStencilVenn2Element extends Components.StencilVenn2, HTMLStencilElement {}
  var HTMLStencilVenn2Element: {
    prototype: HTMLStencilVenn2Element;
    new (): HTMLStencilVenn2Element;
  };

  interface HTMLStencilVenn3Element extends Components.StencilVenn3, HTMLStencilElement {}
  var HTMLStencilVenn3Element: {
    prototype: HTMLStencilVenn3Element;
    new (): HTMLStencilVenn3Element;
  };

  interface HTMLStencilVennElement extends Components.StencilVenn, HTMLStencilElement {}
  var HTMLStencilVennElement: {
    prototype: HTMLStencilVennElement;
    new (): HTMLStencilVennElement;
  };

  interface HTMLElementTagNameMap {
    'stencil-venn-2': HTMLStencilVenn2Element
    'stencil-venn-3': HTMLStencilVenn3Element
    'stencil-venn': HTMLStencilVennElement
  }

  interface ElementTagNameMap {
    'stencil-venn-2': HTMLStencilVenn2Element;
    'stencil-venn-3': HTMLStencilVenn3Element;
    'stencil-venn': HTMLStencilVennElement;
  }


  export namespace JSX {
    export interface Element {}
    export interface IntrinsicElements extends StencilIntrinsicElements {
      [tagName: string]: any;
    }
  }
  export interface HTMLAttributes extends StencilHTMLAttributes {}

}
